### ISSUE TITLE
Plugin description includes links

### ISSUE THREAD

**Issue by fxbenard** [creativejuiz/juiz-social-post-sharer#2]
With makepot the plugin description is getting translated. Yours hold links! You should remove them

**Comment by creativejuiz** [comment]
Hi.
I can't remove links, it's an arrangement with the first translators that gave their time to help me with this plugin.
But I could use markdown instead of HTML...

**Comment by creativejuiz** [comment]
Oh, I just realized: you are talking about plugin description, and not readme file. Sorry. I'll fix it.
Thank you.
