### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by Kilbourne** [creativejuiz/juiz-social-post-sharer#6]
The plugin raise a js exception: chrome is not defined ( related to bookmark button)

**Comment by creativejuiz** [comment]
Thank you for your report.
In which browser did you find out that message ?

**Comment by Kilbourne** [comment]
Firefox.

I've patched this with  var chrome = !!chrome? chrome: false


2016-03-03 1:44 GMT+01:00 Geoffrey <notifications@github.com>:

**Comment by creativejuiz** [comment]
Thank you for that. It'll be patched at the next version. (should be v 1.5 with new features)
Nice day!
